#!/bin/bash

echo "🚀 GitHub Repository Setup for BERT Suicide Risk Prediction"
echo "=========================================================="
echo ""
echo "📝 Suggested repository name: bert-cantonese-suicide-prediction"
echo ""
echo "🔗 After creating the repository on GitHub, run:"
echo ""
echo "# Add the remote repository"
echo "git remote add origin https://github.com/chefmatteo/bert-cantonese-suicide-prediction.git"
echo ""
echo "# Rename branch to main (GitHub standard)"
echo "git branch -M main"
echo ""
echo "# Push to GitHub"
echo "git push -u origin main"
echo ""
echo "✅ Your code is now ready to push!"
echo "📊 Repository includes:"
echo "   - 3 optimized BERT models (LR, SVM, RF)"
echo "   - Comprehensive documentation"
echo "   - Clean project structure"
echo "   - 10,918+ lines of code"
